source 'http://rubygems.org'

gem 'rake'
gem 'sinatra', '>=1.3.2'
gem 'sinatra-reloader'
gem 'thin'
gem 'sprockets'
gem 'coffee-script'
gem 'sass'
gem 'haml', '>=3.1.5'
gem 'eco'
gem 'syntax', '>=1.0.0'
gem 'pony', '>=1.4'
gem 'activerecord', '>=3.2.5'
gem 'activesupport', '>=3.2.5'
gem 'activemodel', '>=3.2.5'
gem 'rack-flash3'

group :test do 
  gem 'rspec', '>=2.10.0'
  gem 'cucumber', '>=1.2.0'
  gem 'autotest-growl', '>=0.2.16'
  gem 'webrat', '>=0.7.3'
  gem 'factory_girl'
end
